apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operator.tigera.io/v1","kind":"Installation","metadata":{"annotations":{},"name":"default"},"spec":{"calicoNetwork":{"bgp":"Enabled","ipPools":[{"cidr":"10.244.0.0/16","encapsulation":"None","natOutgoing":"Enabled","nodeSelector":"all()"}],"linuxDataplane":"BPF"},"nodeUpdateStrategy":{"rollingUpdate":{"maxUnavailable":"25%"}},"variant":"Calico"}}
  creationTimestamp: "2025-01-01T20:00:57Z"
  finalizers:
  - operator.tigera.io/installation-controller
  - tigera.io/operator-cleanup
  - operator.tigera.io/apiserver-controller
  generation: 3
  name: default
  resourceVersion: "6045"
  uid: 89f9cebd-10a6-4722-9131-8b9b5f0d8254
spec:
  calicoNetwork:
    bgp: Enabled
    hostPorts: Enabled
    ipPools:
    - allowedUses:
      - Workload
      - Tunnel
      blockSize: 26
      cidr: 10.244.0.0/16
      disableBGPExport: false
      disableNewAllocations: false
      encapsulation: None
      name: default-ipv4-ippool
      natOutgoing: Enabled
      nodeSelector: all()
    linuxDataplane: BPF
    multiInterfaceMode: None
    nodeAddressAutodetectionV4:
      firstFound: true
    windowsDataplane: Disabled
  cni:
    ipam:
      type: Calico
    type: Calico
  controlPlaneReplicas: 2
  flexVolumePath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
  kubeletVolumePluginPath: /var/lib/kubelet
  logging:
    cni:
      logFileMaxAgeDays: 30
      logFileMaxCount: 10
      logFileMaxSize: 100Mi
      logSeverity: Info
  nodeUpdateStrategy:
    rollingUpdate:
      maxUnavailable: 25%
    type: RollingUpdate
  nonPrivileged: Disabled
  variant: Calico
status:
  calicoVersion: v3.29.1
  computed:
    calicoNetwork:
      bgp: Enabled
      hostPorts: Enabled
      ipPools:
      - allowedUses:
        - Workload
        - Tunnel
        blockSize: 26
        cidr: 10.244.0.0/16
        disableBGPExport: false
        disableNewAllocations: false
        encapsulation: None
        name: default-ipv4-ippool
        natOutgoing: Enabled
        nodeSelector: all()
      linuxDataplane: BPF
      multiInterfaceMode: None
      nodeAddressAutodetectionV4:
        firstFound: true
      windowsDataplane: Disabled
    cni:
      ipam:
        type: Calico
      type: Calico
    controlPlaneReplicas: 2
    flexVolumePath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
    kubeletVolumePluginPath: /var/lib/kubelet
    logging:
      cni:
        logFileMaxAgeDays: 30
        logFileMaxCount: 10
        logFileMaxSize: 100Mi
        logSeverity: Info
    nodeUpdateStrategy:
      rollingUpdate:
        maxUnavailable: 25%
      type: RollingUpdate
    nonPrivileged: Disabled
    variant: Calico
  conditions:
  - lastTransitionTime: "2025-01-01T20:20:11Z"
    message: All Objects Available
    observedGeneration: 3
    reason: AllObjectsAvailable
    status: "False"
    type: Degraded
  - lastTransitionTime: "2025-01-01T20:20:11Z"
    message: All objects available
    observedGeneration: 3
    reason: AllObjectsAvailable
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-01-01T20:20:11Z"
    message: All Objects Available
    observedGeneration: 3
    reason: AllObjectsAvailable
    status: "False"
    type: Progressing
  mtu: 1500
  variant: Calico
