---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-rbd
  namespace: default
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce # Required if rbd
  resources:
    requests:
      storage: 1Gi
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: test-rbd
#spec:
#  containers:
#    - name: test-rbd
#      image: nginx
#      volumeMounts:
#        - name: test-rbd
#          mountPath: /var/lib/www/html
#  volumes:
#    - name: test-rbd
#      persistentVolumeClaim:
#        claimName: test-rbd
#        readOnly: false
---
# Though DaemonSet, expect only one Pod (due to RWO access), 
# and those of all other nodes having status "Pending".
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: test-rbd
  name: test-rbd
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-rbd
  template:
    metadata:
      labels:
        app: test-rbd
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - name: test-rbd
            mountPath: /var/lib/www/html
      volumes:
        - name: test-rbd
          persistentVolumeClaim:
            claimName: test-rbd
            readOnly: false

