---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-cephfs
  namespace: default
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1Gi
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: test-cephfs
#spec:
#  containers:
#    - name: test-cephfs
#      image: nginx
#      volumeMounts:
#        - name: test-cephfs
#          mountPath: /var/lib/www/html
#  volumes:
#    - name: test-cephfs
#      persistentVolumeClaim:
#        claimName: test-cephfs
#        readOnly: false
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: test-cephfs
  name: test-cephfs
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-cephfs
  template:
    metadata:
      labels:
        app: test-cephfs
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - name: test-cephfs
            mountPath: /var/lib/www/html
      volumes:
        - name: test-cephfs
          persistentVolumeClaim:
            claimName: test-cephfs
            readOnly: false

