apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-pvc
  name: test-pvc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pvc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-pvc
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
