---
## 03-kibana.yaml
## NodePort: 30001 for access outside the cluster (because Calico / kubeadm lacks LoadBalancer)
## Access it from outside: http://<any-node-ip>:30001
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kube-logging
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30001
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kube-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        #image: docker.elastic.co/kibana/kibana:7.17.16
        image: docker.io/bitnami/kibana:7.17.16
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
