# @ /etc/rsyslog.d/99-haproxy.conf
# Ensure the Unix socket input module is loaded
$ModLoad imuxsock
# Use Unix-domain socket
$AddUnixListenSocket /var/lib/haproxy/dev/log
# Send HAProxy messages to a dedicated logfile
:programname, startswith, "haproxy" {
    /var/log/haproxy.log
    stop
}

# Set log-file permissions for rsyslog (out of band) 
# sudo touch /var/log/haproxy.log
# sudo chown syslog:adm /var/log/haproxy.log
# sudo chmod 640 /var/log/haproxy.log
