## @ /etc/rsyslog.d/99-haproxy.conf
## Save HAProxy logs
## Load standard socket input
$ModLoad imuxsock

## Route HAProxy logs to dedicated file
:programname, startswith, "haproxy" {
    /var/log/haproxy.log
    stop
}

## Disable TTY logging : comment out lines like:
#daemon.*;mail.*;\
#       news.err;\
#       *.=debug;*.=info;\
#       *.=notice;*.=warn       |/dev/xconsole
#*.=info;*.=notice;*.=warn      |/dev/xconsole

## Explicitly redirect TTY :
#*.info;mail.none;authpriv.none;cron.none;local0.none;local1.none    -/var/log/messages
