---
# Demonstrate that our NFS export, nfs-client SC, and External Provisioner 
# allow for init containers to set UID:GID and access mode 
# on the NFS-server subdirectory (pv) created dynamically to satisfy the claim (pvc).
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-nfs-secure-claim
  labels:
    app: nfs-secure
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-nfs-secure-pod
  labels:
    app: nfs-secure
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: test-nfs-secure-claim
  initContainers:
    - name: init-volume
      image: busybox
      # @ NFS-server host 
      # UID : id nfsanon : uid=50000(nfsanon) gid=50000(nfsanon) groups=50000(nfsanon)
      # GID : getent group ad-linux-users : ad-linux-users:*:322202601:admin,u2,u1
      command: ["sh", "-c", "chown 50000:322202601 /data && chmod 0770 /data"]
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumeMounts:
        - name: data
          mountPath: /data
          subPathExpr: $(POD_NAME)
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "echo Hello from $(date -u '+%Y-%m-%dT%H:%M:%SZ') >> /data/hello.txt && sleep 100"]
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumeMounts:
        - name: data
          mountPath: /data
          subPathExpr: $(POD_NAME)
      securityContext:
        runAsUser: 50000      # nfsanon
        runAsGroup: 322202601 # ad-linux-users
