---
apiVersion: v1
kind: Service
metadata:
  name: nginx-mock-service
spec:
  selector:
    app: nginx-mock-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-mock-app
  labels:
    app: nginx-mock-app
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

