---
# Demonstrate that our NFS export, nfs-client SC, and External Provisioner 
# allow for init containers to set UID:GID and access mode 
# on the NFS-server subdirectory (pv) created dynamically to satisfy the claim (pvc).
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-nfs-secure-pod
  labels:
    why: test-init-pv
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-nfs-secure-pod
  labels:
    why: test-init-pv
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: test-nfs-secure-pod
  initContainers:
    - name: init-volume
      image: busybox
      # @ NFS-server host 
      # UID : id nfsanon : uid=50000(nfsanon) gid=50000(nfsanon) groups=50000(nfsanon)
      # GID : getent group ad-linux-users : ad-linux-users:*:322202601:admin,u2,u1
      command: ["sh", "-c", "chown 50000:322202601 /mnt/data && chmod 0770 /mnt/data"]
      volumeMounts:
        - name: data
          mountPath: /mnt/data
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "echo Secure write >> /data/hello.txt && sleep 100"]
      volumeMounts:
        - name: data
          mountPath: /data
      securityContext:
        runAsUser: 50000
        runAsGroup: 322202601

