---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: 1.29.6
apiServer:
  timeoutForControlPlane: 1m 
  extraArgs:
  extraVolumes:
  certSANs:
clusterName: lime
controlPlaneEndpoint: "192.168.11.11:8443"
controllerManager:
  extraArgs:
    allocate-node-cidrs: "true"
    cluster-cidr: "10.244.0.0/16"
networking:
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.244.0.0/16"
