version = 2
[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "registry.k8s.io/pause:3.9"
    [plugins."io.containerd.grpc.v1.cri".containerd]
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.configs]
        [plugins."io.containerd.grpc.v1.cri".registry.configs."http://k8s.registry.io"]
          [plugins."io.containerd.grpc.v1.cri".registry.configs."http://k8s.registry.io".tls]
            ca_file = "/etc/containerd/certs.d/k8s.registry.io/ca.crt"
            cert_file = "/etc/containerd/certs.d/k8s.registry.io/client.crt"
            key_file = "/etc/containerd/certs.d/k8s.registry.io/client.key"
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."http://k8s.registry.io"]
          endpoint = ["http://k8s.registry.io"]
