apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: duednm.do7e306d70pjzie1
    apiServerEndpoint: "192.168.11.101:6443"
    caCertHashes:
      - sha256:80edaee5eee656f18d90b2943f7d948380439974b1950efd6385a50c209d332d
  timeout: 5m0s
nodeRegistration:
  name: a2
  criSocket: /var/run/containerd/containerd.sock
controlPlane:
  certificateKey: eff6aace1e22ac5f0eccb1fd113b1b292660ba27006cc0e72d518e774baea869
