#!/usr/bin/env bash
#####################################################################
# PKI : kubeadm init phase certs all
# - Run this script on the init node *only*.
# - Idempotent : Generate PKI once; pull fresh creds per.
# 
# ARGs: K8S_INIT_NODE  K8S_KUBEADM_CONFIG
#####################################################################

node=$1
conf=${2:-kubeadm-config.yaml}
host=$(hostname)

# Generate PKI on the init node *only*
[[ "${host,,}" =~ "${node,,}" ]] || exit 11

# Generate PKI (once) : mTLS certs & keys of control plane
[[ -d /etc/kubernetes/pki ]] || {
    echo 'Generating NEW cluster PKI @ /etc/kubernetes/pki/'
    sudo kubeadm init phase certs all --config $conf
}
# Get the set of ephemeral (2hr) bootstrap creds required by kubeadm init/join
key=$(sudo kubeadm certs certificate-key)
hash=$(openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt \
        |openssl rsa -pubin -outform der 2>/dev/null \
        |openssl dgst -sha256 -hex \
        |sed 's/^.* //' \
)
tkn=$(sudo kubeadm token generate)

# Store these creds in file for its subsequent pull from the admin host
cat <<-EOH |tee Makefile.settings
## This file is DYNAMICALLY GENERATED by make recipe 
export K8S_CERTIFICATE_KEY := $key
export K8S_CA_CERT_HASH    := sha256:$hash
export K8S_BOOTSTRAP_TOKEN := $tkn
EOH
