---
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  file:
    kubeConfigPath: discovery.yaml
nodeRegistration: 
  criSocket: unix:///var/run/containerd/containerd.sock 
  name: THIS_NODE_NAME
  taints: []   ## For no taints
controlPlane:
  localAPIEndpoint: 
    advertiseAddress: THIS_NODE_IP
    bindPort: 6443
  certificateKey: 00517ba8b4f8c1cd885fa03a4302ab65d8f733077ae9aa20ccc2467a236419ae
