apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: 1.29.6
networking:
  serviceSubnet: 10.96.0.0/16
  podSubnet: 10.244.0.0/24
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration  ## /var/lib/kubelet/config.yaml
cgroupDriver: systemd 
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
certificateKey: cbb21d9849cd61c5a476681e5683d69e5dd0c46673843ec1341ffd56428800fb 
bootstrapTokens:
- token: 1b4ks2.oq3x7r69im2115fp
  ttl: 24h
  usages:
  - authentication
  - signing
  groups:
  - system:bootstrappers:kubeadm:default-node-token
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  taints: []    ## No taints on control nodes
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: 1b4ks2.oq3x7r69im2115fp
    apiServerEndpoint: 192.168.11.101:6443
    caCertHashes: 
    - sha256:9174931d5090103dfe61aec7b143d0b9f06f743cb3769571e1c32d45a93a2997
  tlsBootstrapToken: 1b4ks2.oq3x7r69im2115fp 
controlPlane:
  localAPIEndpoint: 
    advertiseAddress: THIS_NODE_IP
    bindPort: 6443
nodeRegistration: 
  criSocket: unix:///var/run/containerd/containerd.sock 
  taints: []   ## For no taints
