apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: 1.29.6
clusterName: lime3
controlPlaneEndpoint: 192.168.11.101:6443
networking:
  serviceSubnet: 10.32.0.0/16
  podSubnet: 10.22.0.0/16
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration  ## /var/lib/kubelet/config.yaml
containerRuntimeEndpoint: unix:///var/run/containerd/containerd.sock
cgroupDriver: systemd # systemd|cgroupfs
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 80
imageMinimumGCAge: 2m
evictionHard:
  nodefs.available: "10%"
  imagefs.available: "15%"
  memory.available: "100Mi"
evictionSoft:
  nodefs.available: "15%"
  imagefs.available: "20%"
evictionSoftGracePeriod:
  nodefs.available: "1m"
  imagefs.available: "1m"
evictionMaxPodGracePeriod: 30
evictionPressureTransitionPeriod: 30s
nodeStatusReportFrequency: 10s
nodeStatusUpdateFrequency: 10s
runtimeRequestTimeout: 2m
volumeStatsAggPeriod: 1m
syncFrequency: 1m
rotateCertificates: true
cpuManagerReconcilePeriod: 10s
fileCheckFrequency: 20s
httpCheckFrequency: 10s
logging:
  flushFrequency: 5s
  verbosity: 1
shutdownGracePeriod: 30s
shutdownGracePeriodCriticalPods: 10s
streamingConnectionIdleTimeout: 0s
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  name: a1 ## Default to hostname
  criSocket: unix:///var/run/containerd/containerd.sock
  taints: []      ## No taints on control nodes
