apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: 1.29.6
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration  ## /var/lib/kubelet/config.yaml
cgroupDriver: systemd 
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
certificateKey: 972ede16c12b34b36db28dcd7a2e445add895b23a15e415952546731e5712bb7 
bootstrapTokens:
- token: e6fb1a.rbuwqmef7f18knl2
  ttl: 24h
  usages:
  - authentication
  - signing
  groups:
  - system:bootstrappers:kubeadm:default-node-token
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  taints: []    ## No taints on control nodes
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: e6fb1a.rbuwqmef7f18knl2
    apiServerEndpoint: 192.168.11.101:6443
    caCertHashes: 
    - sha256:a7c7ffc733300b2727ba82660d8fafde6f9b3f46edcf82592fd987c4de0b3d33
  tlsBootstrapToken: e6fb1a.rbuwqmef7f18knl2 
nodeRegistration: 
  criSocket: unix:///var/run/containerd/containerd.sock 
  taints: []   ## For no taints
