#!/usr/bin/env bash
##############################################
# PKI : kubeadm init phase certs all 
# 
# - Generate PKI once.
# - Run this script on the init node *only*.
# - Idempotent
# 
# ARGs: K8S_KUBEADM_CONF_INIT
##############################################
[[ "$(id -u)" -ne 0 ]] && {
    echo "⚠️  ERR : MUST run as root" >&2

    exit 11
}
[[ -r $1 ]] || exit 22

[[ -d /etc/kubernetes/pki/etcd ]] ||
    kubeadm init phase certs all -v5 --config $1

exit
####
#####################################################
# UPDATE : Capture certificate key from init-now log
#####################################################

# Generate a new key
CERT_KEY="$(kubeadm certs certificate-key)"

# Save it for subsequent init/join config
target=Makefile.settings
cat <<-EOH |tee $target
## This file is DYNAMICALLY GENERATED by make recipe 
export K8S_CERTIFICATE_KEY := $CERT_KEY
EOH
