## kubeadm join --discovery-file /path/to/this/file
## This file is build from kubeconfig extracts
apiVersion: v1
kind: Config
clusters:
- name: kubernetes
  cluster:
    certificate-authority-data: <base64-encoded-CA-cert>
    server: https://<control-plane-endpoint>:6443
contexts:
- name: default
  context:
    cluster: kubernetes
current-context: default
