apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: 1.29.6
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration  ## /var/lib/kubelet/config.yaml
cgroupDriver: systemd 
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
certificateKey: 972ede16c12b34b36db28dcd7a2e445add895b23a15e415952546731e5712bb7 
bootstrapTokens:
- token: e6fb1a.rbuwqmef7f18knl2
  ttl: 24h
  usages:
  - authentication
  - signing
  groups:
  - system:bootstrappers:kubeadm:default-node-token
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  taints: []    ## No taints on control nodes
