---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: nfs-client  # Matches the provisioner's StorageClass
  accessModes:
    - ReadWriteOnce  # Or ReadWriteMany if your NFS supports it
  resources:
    requests:
      storage: 10Gi  # Adjust size as needed
