allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: nfs-provisioner
    meta.helm.sh/release-namespace: kube-system
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    app: nfs-subdir-external-provisioner
    app.kubernetes.io/managed-by: Helm
    chart: nfs-subdir-external-provisioner-4.0.18
    heritage: Helm
    release: nfs-provisioner
  name: nfs-client
parameters:
  archiveOnDelete: "true"
  #mountOptions: "dir_mode=0770,file_mode=0660"
provisioner: cluster.local/nfs-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
