#!/usr/bin/env bash
###############################################################
# Create LVM-based data store for NFS export on a RHEL8+ host
# - Idempotent
###############################################################
[[ $(whoami) == 'root' ]] || {
    echo "❌  ERR : Must RUN AS root"
    
    exit 11
}

##############################################
# Create LVM-based store on (raw) block device

dev=/dev/sdb
vg=data
lv=nfs1

# 1. Create the Physical Volume  (PV)
pvs $dev ||
    pvcreate $dev

# 2. Create the Volume Group     (VG)
vgs $vg ||
    vgcreate $vg $dev

# 3. Create a Logical Volume     (LV)
lvs $vg ||
    lvcreate -n $lv -l "100%FREE" $vg
    #... keywork "100%FREE" uses all remaining unallocated extents of VG

# 4. Create FS : Format as XFS
blkid /dev/$vg/$lv |grep xfs ||
    mkfs.xfs /dev/$vg/$lv

###############
## Create mount

export=/srv/nfs/k8s
user=nfsanon
group=ad-nfsanon

# 1. Create mount point and mount ephemerally if not already
mkdir -p $export &&
    mount |grep $export >/dev/null 2>&1 || {
        mount /dev/$vg/$lv $export || {
            echo "❌  ERR : FAIL @ mount /dev/$vg/$lv $export"

            exit 22
        }
    }

# 2. Set proper SELinux fcontext for R/W access at container mounts, if applicable.
command -v getenforce >/dev/null 2>&1 &&
    semanage fcontext -a -t public_content_rw_t "${export}(/.*)?" &&
        restorecon -Rv "$export"

## Persist

# 3. Get UUID
blkid="$(blkid /dev/$vg/$lv |cut -d' ' -f2 |cut -d'=' -f2 |sed 's/"//g')"
[[ $blkid ]] || {
    echo "❌  ERR : FAIL @ blkid /dev/$vg/$lv"

    exit 33
}

# 4. Append to /etc/fstab (once)
grep "$blkid" /etc/fstab >/dev/null 2>&1 || tee -a /etc/fstab <<-EOH
UUID=$blkid $export xfs defaults 0 0
EOH

# 5. Apply changes to the systemd unit file (.mount) generated by systemd-fstab-generator
svc=${export////-}.mount
svc=${svc:1}
systemctl daemon-reload &&
    systemctl is-active $svc || {
        echo "❌  ERR : systemctl : $svc"
        systemctl cat $svc

        exit 44
    }

# 6. Mount and initialize
mount -a &&
    chown -R "$user:$group" "$export"
