#!/usr/bin/env bash
##########################################################
# Create LVM-based data store for NFS 
# - Idempotent
##########################################################
dev=/dev/sdb
vg=data
lv=nfs1
export=/srv/nfs/k8s

# Create the Physical Volume  (PV)
sudo pvs $dev ||
    sudo pvcreate $dev

# Create the Volume Group     (VG)
sudo vgs $vg ||
    sudo vgcreate $vg /dev/sdb

# Create a Logical Volume     (LV)
sudo lvs $vg ||
    sudo lvcreate -n $lv -l "100%FREE" $vg
    #... keywork "100%FREE" uses all remaining unallocated extents of VG

# Create FS : Format as XFS
sudo blkid /dev/$vg/$lv |grep xfs ||
    sudo mkfs.xfs /dev/$vg/$lv

# Create mount point and mount ephemerally
sudo mkdir -p $export &&
    sudo mount /dev/$vg/$lv $export

# Persist
# 1. Get UUID
blkid="$(sudo blkid /dev/$vg/$lv |cut -d' ' -f2 |cut -d'=' -f2 |sed 's/"//g')"
# 2. Append to /etc/fstab (once)
cat /etc/fstab |grep $blkid || cat <<EOH |sudo tee -a /etc/fstab
UUID=$blkid $export xfs defaults 0 0
EOH
# 3. Apply changes to systemd srv-nfs-k8s.mount, 
#    which is dynamically generated by systemd-fstab-generator
sudo systemctl daemon-reload &&
    systemctl cat srv-nfs-k8s.mount
# 4. Mount and initialize
sudo mount -a &&
    sudo chown -R nfsanon:ad-linux-users $export

